---
- name: Make this server pull packages from the local server, not from accross the internet
  hosts: cluster1
  remote_user: anton
  vars:
    ansible_ssh_pass: "password"
  become: true

  tasks:
    - name: Configure YUM/DNF to Use the Local Repository
      copy:
        content: |
          [local]
          name=local_ol9_baseos_latest
          baseurl=http://10.0.0.5/newrepo/
          enabled=1
          gpgcheck=0
        dest: /etc/yum.repos.d/local.repo
      become: yes
