---
- name: Sync RHEL 9 Local Package Repository
  hosts: localhost
  become: true

  tasks:
    - name: Create Repository Directory
      file:
        path: /home/anton/repo
        state: directory
      become: yes

    - name: Fetch all RPM Packages from Remote Server
      find:
        paths: /home/anton/repo
        patterns: "*.rpm"
      register: rpm_packages

    - name: Fetch RPM Packages from Remote Server
      get_url:
        url: "https://yum.oracle.com/repo/OracleLinux/OL9/baseos/latest/x86_64/{{ item.path }}"
        dest: "/home/anton/repo/{{ item.path | basename }}"
      with_items: "{{ rpm_packages.files }}"

    - name: Install createrepo Package
      dnf:
        name: createrepo
        state: present
      become: yes

    - name: Create Repository Metadata
      command: createrepo /home/anton/repo
      become: yes

    # Optional: Set up a web server (e.g., httpd) to make the repository accessible over the network
    - name: Install httpd Package
      dnf:
        name: httpd
        state: present
      become: yes

    - name: Copy Repository to Web Server Directory
      command: cp -r /home/anton/repo /var/www/html/
      become: yes

    - name: Start and Enable httpd Service
      systemd:
        name: httpd
        state: started
        enabled: yes
      become: yes

    - name: Configure YUM/DNF to Use the Local Repository
      copy:
        content: |
          [local]
          name=local_ol9_baseos_latest
          baseurl=http://10.0.0.5/repo   # Update with your actual server URL
          enabled=1
          gpgcheck=0  # Change to 1 if you sign your packages
        dest: /etc/yum.repos.d/local.repo
      become: yes

    - name: Test Local Repository
      dnf:
        name: '*'
        state: latest
