---
- name: Local RHEL9 package repository setup. Fetch packages and expose with httpd
  hosts: localhost
  become: true
  vars:
    local_repo_path: /home/anton/newrepo

  tasks:
    - name: Install yum utils
      dnf:
        name: yum-utils
        state: present
      become: yes
      
    - name: Create Repository Directory
      file:
        path: "{{ local_repo_path }}"
        state: directory
      become: yes

    - name: Download all latest versions of packages from the repository and place it in the local directory
      ansible.builtin.shell: sudo reposync -n -p "{{ local_repo_path }}" --repoid=ol9_baseos_latest --repoid=ol9_baseos_latest
      become: yes

    - name: Install createrepo Package
      dnf:
        name: createrepo
        state: present
      become: yes

    - name: Create Repository Metadata
      command: createrepo "{{ local_repo_path }}"
      become: yes

    # Set up a web server (httpd) to make the repository accessible over the network
    - name: Install httpd Package
      dnf:
        name: httpd
        state: present
      become: yes

    - name: Copy Repository to Web Server Directory
      command: cp -r "{{ local_repo_path }}" /var/www/html/
      become: yes

    - name: Start and Enable httpd Service
      systemd:
        name: httpd
        state: started
        enabled: yes
      become: yes
