---
- name: Make this server pull packages from the local server, not from accross the internet
  hosts: cluster1
  remote_user: anton
  vars:
    ansible_ssh_pass: "password"
    ansible_become_pass: "password"
  become: true

  tasks:
    - name: Configure YUM/DNF to Use the Local Repository
      copy:
        content: |
          [local]
          name=local_ol9_baseos_latest
          baseurl=http://10.0.0.5/newrepo/
          enabled=1
          gpgcheck=1
        dest: /etc/yum.repos.d/local.repo
      become: yes
      
    - name: Disable a remote ol9 repo
      ini_file:
        path: /etc/yum.repos.d/oracle_linux_ol9.repo  # Replace with the actual repository file path
        section: repository
        option: enabled
        value: 0
