---
- name: Build and publish local OEL/RHEL 9 repositories (BaseOS, AppStream, EPEL) on NFS
  hosts: localhost
  connection: local
  become: true

  vars:
    # NFS-backed storage for the repo content + metadata
    repo_root: /mnt/repos

    # Where httpd will serve repos from (symlink → repo_root)
    http_repo_root: /var/www/html/repos

    mirrored_repos:
      - name: BaseOS
        repoid: ol9_baseos_latest
      - name: AppStream
        repoid: ol9_appstream
      - name: EPEL
        repoid: ol9_developer_EPEL    # <- correct EPEL repo ID on OL9

  tasks:

    - name: Install required packages for mirroring and serving repos
      dnf:
        name:
          - yum-utils     # reposync
          - createrepo    # repodata
          - httpd         # web server
        state: present

    # Ensure the NFS mount is present BEFORE this (fstab or separate task)
    - name: Ensure NFS-backed repo root directory exists
      file:
        path: "{{ repo_root }}"
        state: directory
        mode: '0755'

    - name: Ensure subdirectories exist for each mirrored repo on NFS
      file:
        path: "{{ repo_root }}/{{ item.repoid }}"
        state: directory
        mode: '0755'
      loop: "{{ mirrored_repos }}"

    - name: Sync each configured repository with reposync into NFS
      command: >
        reposync -n -p "{{ repo_root }}/{{ item.repoid }}"
        --repoid={{ item.repoid }}
        --download-metadata
      loop: "{{ mirrored_repos }}"

    - name: Create repository metadata for each local repo on NFS
      command: createrepo "{{ repo_root }}/{{ item.repoid }}"
      # If you really want to only create once, uncomment creates:
      # args:
      #   creates: "{{ repo_root }}/{{ item.repoid }}/repodata"
      loop: "{{ mirrored_repos }}"

    - name: Ensure parent directory for Apache repo symlink exists
      file:
        path: "{{ http_repo_root | dirname }}"
        state: directory
        mode: '0755'

    - name: Point Apache repo directory to NFS repo root via symlink
      file:
        src: "{{ repo_root }}"
        dest: "{{ http_repo_root }}"
        state: link
        force: yes

    - name: Allow httpd to read NFS content (SELinux)
      command: setsebool -P httpd_use_nfs 1
      when: ansible_selinux is defined and ansible_selinux.status == "enabled"

    - name: Start and enable httpd
      systemd:
        name: httpd
        state: started
        enabled: yes
