---
- name: Demo02 - Making packages present and then absent 
  hosts: cluster02        # The name of the group of hosts we're going to work on 
  become: true            # Gain root privileges to run the command 

  tasks:
    - name: Install btop 
      apt:
        name:
          -  btop
        state: present  
