---
- name: Demo05 - Install and configure chrony on supported Linux hosts
  hosts:
    - cluster05ubuntu
    - cluster05oel
  become: true

  vars:
    chrony_package: chrony

  tasks:
    - name: Fail if OS family is not supported
      ansible.builtin.fail:
        msg: "Unsupported OS family: {{ ansible_facts['os_family'] }}. This playbook only supports RedHat and Debian."
      when: ansible_facts['os_family'] not in ['RedHat', 'Debian']

    # ---------- RedHat / OEL9 ----------
    - name: Set variables for RedHat family
      ansible.builtin.set_fact:
        chrony_service: chronyd
        chrony_conf_path: /etc/chrony.conf
        chrony_conf_src: chrony.conf
      when: ansible_facts['os_family'] == 'RedHat'

    # ---------- Debian / Ubuntu 24 ----------
    - name: Set variables for Debian family
      ansible.builtin.set_fact:
        chrony_service: chrony
        chrony_conf_path: /etc/chrony/chrony.conf
        chrony_conf_src: chrony.conf
      when: ansible_facts['os_family'] == 'Debian'

    # ---------- Install ----------
    - name: Ensure chrony is installed
      ansible.builtin.package:
        name: "{{ chrony_package }}"
        state: present
        update_cache: "{{ ansible_facts['os_family'] == 'Debian' }}"

    # ---------- Deploy Config ----------
    - name: Push customised chrony.conf
      ansible.builtin.copy:
        src: "{{ chrony_conf_src }}"
        dest: "{{ chrony_conf_path }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart chrony

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: "{{ chrony_service }}"
        state: restarted
        enabled: true
