---
- name: Introduction to writing playbooks 
  hosts: cluster01        # The name of the group of hosts we're going to work on 
  become: true            # Gain root privileges to run the command 

  tasks:
    - name: Install some basic packages
      apt:
        name:
          -  btop
        state: present
