---
- name: Demo05 - reset the hosts 
  hosts:
    - cluster05oel
    - cluster05ubuntu 
  become: true
  gather_facts: true

  vars:
    chrony_service: >-
      {{ 'chronyd' if ansible_facts['os_family'] == 'RedHat' else 'chrony' }}

  tasks:
    - name: Stop and disable chrony service if present
      ansible.builtin.service:
        name: "{{ chrony_service }}"
        state: stopped
        enabled: false
      ignore_errors: true  # in case service/unit doesn't exist

    - name: Remove chrony package
      ansible.builtin.package:
        name: chrony
        state: absent

    - name: Reload systemd daemon (optional but nice)
      ansible.builtin.systemd:
        daemon_reload: true
      when: ansible_facts['os_family'] == 'RedHat'
